version: '3.8'
services:
  insurance_card_managenent_system:
    image: postgres:13
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: cosc2440
      POSTGRES_DB: insurance_card
    networks:
      - rmit
networks:
  rmit:
